SELECT * FROM MEMBER;
SELECT * FROM GRADE;
SELECT * FROM PRODUCT;
SELECT * FROM WISHLIST;
SELECT * FROM SERIAL;
SELECT * FROM BUYPRODUCT;
SELECT * FROM CART;
SELECT * FROM ADDRESS;
SELECT * FROM REVIEW;


DROP TABLE MEMBER;
DROP TABLE GRADE;
DROP TABLE PRODUCT;
DROP TABLE WISHLIST;
DROP TABLE SERIAL;
DROP TABLE BUYPRODUCT;
DROP TABLE CART;
DROP TABLE ADDRESS;
DROP TABLE REVIEW;



INSERT INTO REVIEW (RPK,MID,PPK,CONTENT,SCOPE,IMG) VALUES ((SELECT NVL(MAX(RPK),0)+1 FROM REVIEW),'user',3,'굿',5,'사진');

SELECT R.CONTENT, R.SCOPE, R.IMG, R.REGDATE, M.NICKNAME, M.GPK 
FROM REVIEW R JOIN MEMBER M
ON(R.MID = M.MID)
WHERE R.PPK=1;

SELECT B.CNT, B.SPK, S.REGDATE, P.PNAME, P.PRICE, P.IMG, P.PPK, S.DELIVERYADDRESS
FROM BUYPRODUCT B JOIN SERIAL S
ON(B.SPK=S.SPK) 
JOIN PRODUCT P ON(B.PPK=P.PPK) 
WHERE S.MID='qwe';

INSERT INTO ADDRESS (APK, MID, ZONECODE, JIBUNADDRESS, ROADADDRESS, DETAIL, ANAME) VALUES ((SELECT NVL(MAX(APK),0)+1 FROM ADDRESS),?, ?, ?, ?, ?,?)

INSERT INTO ADDRESS (APK, MID, ZONECODE, JIBUNADDRESS, ROADADDRESS, DETAIL, ANAME) VALUES ((SELECT NVL(MAX(APK),0)+1 FROM ADDRESS),'qwe', '03125', '서울', '강남', '101호','두번쨰집');

SELECT APK, ZONECODE, JIBUNADDRESS, ROADADDRESS, DETAIL, ANAME FROM ADDRESS WHERE MID = 'qwe';

SELECT ZONECODE, JIBUNADDRESS, ROADADDRESS, DETAIL, ANAME FROM ADDRESS WHERE APK = 1;

UPDATE ADDRESS SET ZONECODE=?, JIBUNADDRESS=?, ROADADDRESS=?, DETAIL=?, ANAME=? WHERE APK=?

UPDATE ADDRESS SET ZONECODE='03252', JIBUNADDRESS='경기도', ROADADDRESS='가평', DETAIL='101', ANAME='회사' WHERE APK='1';

SELECT APK, ZONECODE, JIBUNADDRESS, DETAIL, ADDRESSNAME FROM ADDRESS WHERE MID = 'qwe';

INSERT INTO ADDRESS VALUES ((SELECT NVL(MAX(APK),0)+1 FROM ADDRESS),MID, ZONECODE, JIBUNADDRESS, ROADADDRESS, DETAIL);
INSERT INTO ADDRESS VALUES ((SELECT NVL(MAX(APK),0)+1 FROM ADDRESS),'qwe', '02030', '서울 지번 ', '서울 도로명', '13층');

INSERT INTO REVIEW (RPK,MID,PPK,CONTENT,SCOPE,IMG) VALUES ((SELECT NVL(MAX(RPK),0)+1 FROM REVIEW),'qwe',23,'죠스바',5,'사진100');

SELECT P.PPK, P.PNAME, P.PRICE, P.IMG FROM PRODUCT P LEFT OUTER JOIN (SELECT PPK, COUNT(PPK) CNT FROM WISHLIST GROUP BY PPK) W ON (P.PPK=W.PPK) ORDER BY P.REGDATE DESC, P.PPK DESC;

SELECT R.CONTENT, R.SCOPE, R.IMG, R.REGDATE, M.NICKNAME, M.GPK FROM REVIEW R 
JOIN MEMBER M ON(R.MID = M.MID) WHERE R.PPK=6;

SELECT MID, MPW, NAME, BIRTH, PHONE, NICKNAME, EMAIL, MARKETING, GPK FROM MEMBER WHERE NICKNAME='테스트1';

SELECT NVL(WISHLIST.WPK,0) AS WISH,
P.PPK, P.PNAME, P.PRICE, P.IMG, W.CNT FROM PRODUCT P 
LEFT OUTER JOIN (SELECT PPK, COUNT(PPK) CNT FROM WISHLIST GROUP BY PPK) W 
ON P.PPK=W.PPK  
LEFT OUTER JOIN WISHLIST ON WISHLIST.PPK=P.PPK AND WISHLIST.MID='qwe'
ORDER BY  NVL(W.CNT, 0) DESC, P.PPK DESC; --찜순으로 정렬

SELECT W.WPK, W.MID, P.PPK, P.PNAME, P.PRICE, P.IMG
FROM WISHLIST W
JOIN PRODUCT P ON W.PPK = P.PPK
WHERE W.MID = 'qwe'; --찜 보여주는 조인문

--높은 가격순
SELECT PPK, PNAME, PRICE, IMG FROM PRODUCT 
	ORDER BY PRICE DESC; 
	
--낮은 가격순
SELECT PPK, PNAME, PRICE, IMG FROM PRODUCT 
	ORDER BY PRICE ASC; 

